### ISSUE TITLE
mysql2 error

### ISSUE THREAD

**Issue by chabgood** [jsuchal/activerecord-fast-import#4]
Mysql2::Error: The used command is not allowed with this MySQL version: LOAD DATA LOCAL INFILE '/Users/chabgood/projects/health_tracker/db/icd9.csv' INTO TABLE `conditions` (icd9, long_description, short_description)

**Comment by jsuchal** [comment]
Which Mysql version are you using?

**Comment by chabgood** [comment]
Server version: 5.5.20 MySQL Community Server (GPL)

Copyright (c) 2000, 2010, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

On Tue, Apr 3, 2012 at 02:35, Jn Suchal <
reply@reply.github.com

> wrote:
> 
> Which Mysql version are you using?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jsuchal/activerecord-fast-import/issues/4#issuecomment-4895948

## 

*"In matters of style, swim with the current; in matters of principle,
stand like a rock."
Thomas Jefferson
*

**Comment by jsuchal** [comment]
Hi,

please make sure LOAD DATA INFILE is not disabled on your server or client.

> If LOAD DATA LOCAL is disabled, either in the server or the client, a client that attempts to issue such a statement receives the following error message:
> ERROR 1148: The used command is not allowed with this MySQL version
> http://dev.mysql.com/doc/refman/5.5/en/load-data-local.html

**Comment by chabgood** [comment]
I have a ruby script that uses command to load data from some files and it
works.  Did you verify your gem works with the mysql2 gem?

On Tue, Apr 3, 2012 at 08:30, Jn Suchal <
reply@reply.github.com

> wrote:
> 
> Hi,
> 
> please make sure LOAD DATA INFILE is not disabled.
> 
> > If LOAD DATA LOCAL is disabled, either in the server or the client, a
> > client that attempts to issue such a statement receives the following error
> > message:
> > ERROR 1148: The used command is not allowed with this MySQL version
> > http://dev.mysql.com/doc/refman/5.5/en/load-data-local.html
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jsuchal/activerecord-fast-import/issues/4#issuecomment-4901179

## 

*"In matters of style, swim with the current; in matters of principle,
stand like a rock."
Thomas Jefferson
*

**Comment by jsuchal** [comment]
Could you provide me a gist of your script that I can test?

**Comment by chabgood** [comment]
class LoadICD9

  def load_icd9

ActiveRecord::Base.connection.execute(load_data_infile_icd9("#{Rails.root}/db/icd9.csv"))
  end

  def load_conditions

ActiveRecord::Base.connection.execute(load_data_conditions("#{Rails.root}/db/conditions.txt"))
  end

  private

  def load_data_conditions(path)
     <<-EOF
       LOAD DATA INFILE "#{path}" IGNORE
          INTO TABLE conditions
             (name)
            SET created_at = '#{Time.current.to_s(:db)}',
            updated_at = '#{Time.current.to_s(:db)}';
      EOF
  end

  def load_data_infile_icd9(path)
     <<-EOF
       LOAD DATA INFILE "#{path}" IGNORE
          INTO TABLE conditions
          FIELDS TERMINATED BY ','
          ENCLOSED BY '"'
             (icd9,name,description)
            SET created_at = '#{Time.current.to_s(:db)}',
            updated_at = '#{Time.current.to_s(:db)}';
      EOF
  end
end
l = LoadICD9.new
l.load_icd9
l.load_conditions

On Tue, Apr 3, 2012 at 08:42, Jn Suchal <
reply@reply.github.com

> wrote:
> 
> Could you provide me a gist of your script that I can test?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jsuchal/activerecord-fast-import/issues/4#issuecomment-4901414

## 

*"In matters of style, swim with the current; in matters of principle,
stand like a rock."
Thomas Jefferson
*

**Comment by jsuchal** [comment]
Aha! You are not using LOCAL, thats a different command. Do you load data from client filesystem or server filesystem?

**Comment by chabgood** [comment]
Well the odd thing is that I can use the LOCAL command on my centos server
but not on my mac box.  kinda odd.  using mysql 5.1 on centos.  The files
are local in my db directory.  Rails app.

On Tue, Apr 3, 2012 at 08:50, Jn Suchal <
reply@reply.github.com

> wrote:
> 
> Aha! You are not using LOCAL, thats a different command. Do you load data
> from client filesystem or server filesystem?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jsuchal/activerecord-fast-import/issues/4#issuecomment-4901556

## 

*"In matters of style, swim with the current; in matters of principle,
stand like a rock."
Thomas Jefferson
*
